import type { Metadata } from "next";
import Header from "../components/header";
import { Sidebar } from "./students/components/sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <header><Header /></header>
            <main>
                <aside className="card"><Sidebar /></aside>
                <section>{children}</section>
            </main>
            {/* <footer><Footer /></footer> */}
        </>
    );
}
